# left menu locator
menu_newOffer = "xpath://fuse-navigation//*[contains(text(),'New Offers')]"
menu_myShipment = "xpath://fuse-navigation//*[contains(text(),'My Shipments')]"
menu_dashboard = "xpath://fuse-navigation//*[contains(text(),'Dashboard')]"
menu_mapView = "xpath://fuse-navigation//*[contains(text(),'Map View')]"
menu_myDispatcher = "xpath://fuse-navigation//*[contains(text(),'My Dispatcher')]"
menu_myDriver = "xpath://fuse-navigation//*[contains(text(),'My Driver')]"
menu_myTruck = "xpath://fuse-navigation//*[contains(text(),'My Truck')]"
menu_myPurchaseOrder = "xpath://fuse-navigation//*[contains(text(),'My Purchase Orders')]"
menu_myPayment = "xpath://fuse-navigation//*[contains(text(),'My Payments')]"
menu_uploadEPOD = "xpath://fuse-navigation//*[contains(text(),'Upload ePOD')]"
menu_report = "xpath://fuse-navigation//*[contains(text(),'Reports')]"
menu_carrierLedgerReport = "xpath://fuse-navigation//*[contains(text(),'Carrier Ledger Report')]"
menu_shipmentReport = "xpath://fuse-navigation//*[contains(text(),'Shipment Report')]"
menu_paymentStatusReport = "xpath://fuse-navigation//*[contains(text(),'Payment Status Report')]"
menu_restApi = "xpath://fuse-navigation//*[contains(text(),'REST API')]"
